# Generated by Django 4.1.1 on 2022-10-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(default='No description', max_length=2000, null=True, verbose_name='Description')),
                ('photo', models.CharField(default='No photo', max_length=500, null=True, verbose_name='Image')),
                ('category', models.CharField(choices=[('Ph', 'Phones'), ('Acc', 'Accumulators'), ('Nb', 'Notebooks'), ('O', 'Others')], default='Others', max_length=20, verbose_name='Category')),
                ('balance', models.PositiveIntegerField(verbose_name='Balance')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Date of change')),
            ],
        ),
    ]
