# Generated by Django 4.1.1 on 2022-10-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_good_deleted_at_good_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.CharField(choices=[('Phones', 'Телефоны'), ('Accumulators', 'Аккумуляторы'), ('Notebooks', 'Ноутбуки'), ('Others', 'Другие')], default='Others', max_length=20, verbose_name='Category'),
        ),
    ]
