# Generated by Django 4.1.1 on 2022-10-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_good_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date of delete'),
        ),
        migrations.AlterField(
            model_name='good',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Date of change')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Date of delete')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='shop_app.good', verbose_name='Product')),
            ],
        ),
    ]
